"""
Learning packages: the concept map, lesson and questions for a topic.

A package is generated by Gemini the first time anyone searches a
topic, saved to the database, and reused after that, so each topic
costs one generation call no matter how many times it's played.
"""

import json
import sqlite3
from contextlib import closing

from db import get_db
from gemini_api import generate_learning_package, normalize_label, slugify
from mastery import DIFFICULTY_BY_TYPE


# Searches already matched to a saved topic, e.g. "how do volcanoes
# erupt" -> the "Volcanic Eruptions" topic, so typing the same thing
# again skips the Gemini matching call. In memory, per server run.
_topic_for_search = {}


def find_or_create_topic(typed_topic):
    """
    Return the topic_id for what the student typed, generating and
    saving a new package if this topic hasn't been seen before.

    Returns None if a new package couldn't be generated.
    """
    typed_topic = typed_topic.strip()

    search_slug = slugify(typed_topic)

    with closing(get_db()) as conn:

        # Exact match on the slug: "python loops" == "Python Loops".
        row = conn.execute(
            "SELECT topic_id FROM topics WHERE slug = ?",
            (search_slug,)
        ).fetchone()

        if row:
            return row["topic_id"]

        if search_slug in _topic_for_search:
            return _topic_for_search[search_slug]

        # Same topic, worded differently: "loops in python".
        titles = [
            r["title"] for r in
            conn.execute("SELECT title FROM topics").fetchall()
        ]

    canonical = normalize_label(typed_topic, titles, label_type="topic")

    if canonical in titles:
        with closing(get_db()) as conn:
            topic_id = conn.execute(
                "SELECT topic_id FROM topics WHERE title = ?",
                (canonical,)
            ).fetchone()["topic_id"]

        _topic_for_search[search_slug] = topic_id

        return topic_id

    package = generate_learning_package(canonical)

    if not package:
        return None

    # Key the topic by what was searched, not Gemini's title, so the
    # same search finds it again without another Gemini call.
    topic_id = save_package(package, slugify(canonical))

    if topic_id:
        _topic_for_search[search_slug] = topic_id

    return topic_id


def save_package(package, slug):
    """Store a validated package under `slug` and return its topic_id."""

    try:
        with closing(get_db()) as conn, conn:

            cursor = conn.execute(
                "INSERT INTO topics (slug, title, explanation, lesson) "
                "VALUES (?, ?, ?, ?)",
                (slug, package["title"].strip(),
                 package["explanation"], package["lesson"])
            )
            topic_id = cursor.lastrowid

            concept_ids = {}

            for position, concept in enumerate(package["concepts"], start=1):
                cursor = conn.execute(
                    """
                    INSERT INTO concepts (topic_id, slug, name, description,
                        learning_objective, difficulty, position,
                        prerequisites_json)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (topic_id, concept["id"], concept["name"],
                     concept["description"], concept["learning_objective"],
                     concept["difficulty"], position,
                     json.dumps(concept["prerequisites"]))
                )
                concept_ids[concept["id"]] = cursor.lastrowid

            for position, question in enumerate(package["questions"], start=1):
                conn.execute(
                    """
                    INSERT INTO questions (topic_id, concept_id, position,
                        question_type, difficulty, question, options_json,
                        answer, source)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'package')
                    """,
                    (topic_id, concept_ids[question["concept"]], position,
                     question["question_type"],
                     DIFFICULTY_BY_TYPE[question["question_type"]],
                     question["question"], json.dumps(question["options"]),
                     question["answer"])
                )

        return topic_id

    except sqlite3.IntegrityError:
        # Someone else saved the same topic a moment earlier.
        with closing(get_db()) as conn:
            row = conn.execute(
                "SELECT topic_id FROM topics WHERE slug = ?", (slug,)
            ).fetchone()

        if row:
            return row["topic_id"]

        raise


def load_package(topic_id):
    """
    Return the saved package for a topic:

    {
        "topic_id", "title", "explanation", "lesson",
        "concepts": [ {concept_id, slug, name, description,
                       learning_objective, difficulty, position,
                       prerequisites: [names]} ],   # prerequisite order
        "questions": [ {question_id, concept_id, question_type,
                        difficulty, question, options, answer} ]
    }

    Returns None if the topic doesn't exist.
    """
    with closing(get_db()) as conn:

        topic = conn.execute(
            "SELECT topic_id, title, explanation, lesson "
            "FROM topics WHERE topic_id = ?",
            (topic_id,)
        ).fetchone()

        if not topic:
            return None

        concept_rows = conn.execute(
            "SELECT * FROM concepts WHERE topic_id = ? ORDER BY position",
            (topic_id,)
        ).fetchall()

        question_rows = conn.execute(
            "SELECT * FROM questions "
            "WHERE topic_id = ? AND source = 'package' ORDER BY position",
            (topic_id,)
        ).fetchall()

    names = {row["slug"]: row["name"] for row in concept_rows}

    concepts = [
        {
            "concept_id": row["concept_id"],
            "slug": row["slug"],
            "name": row["name"],
            "description": row["description"],
            "learning_objective": row["learning_objective"],
            "difficulty": row["difficulty"],
            "position": row["position"],
            "prerequisites": [
                names[slug]
                for slug in json.loads(row["prerequisites_json"])
                if slug in names
            ]
        }
        for row in concept_rows
    ]

    questions = [question_from_row(row) for row in question_rows]

    return {
        "topic_id": topic["topic_id"],
        "title": topic["title"],
        "explanation": topic["explanation"],
        "lesson": topic["lesson"],
        "concepts": concepts,
        "questions": questions
    }


def question_from_row(row):
    return {
        "question_id": row["question_id"],
        "concept_id": row["concept_id"],
        "question_type": row["question_type"],
        "difficulty": row["difficulty"],
        "question": row["question"],
        "options": json.loads(row["options_json"]),
        "answer": row["answer"]
    }


def save_remediation_question(topic_id, concept_id, question_type,
                              difficulty, question):
    """
    Store a Gemini remediation question so attempts can refer to it.
    Returns the question in the same shape as load_package().
    """
    with closing(get_db()) as conn, conn:
        cursor = conn.execute(
            """
            INSERT INTO questions (topic_id, concept_id, position,
                question_type, difficulty, question, options_json,
                answer, source)
            VALUES (?, ?, NULL, ?, ?, ?, ?, ?, 'remediation')
            """,
            (topic_id, concept_id, question_type, difficulty,
             question["question"], json.dumps(question["options"]),
             question["answer"])
        )

        row = conn.execute(
            "SELECT * FROM questions WHERE question_id = ?",
            (cursor.lastrowid,)
        ).fetchone()

    return question_from_row(row)
